.PHONY: setup-android build-android build-android-release sign-apk release-android clean start start-debug stop restart logs migrate reconcile bump-android-version monitoring-up monitoring-down monitoring-logs monitoring-reload monitoring-check

ANDROID_SDK_PATH ?= $(if $(wildcard $(HOME)/Android/Sdk),$(HOME)/Android/Sdk,$(HOME)/Library/Android/sdk)
JAVA_HOME ?= $(if $(wildcard /usr/lib/jvm/java-21-openjdk-amd64/bin/javac),/usr/lib/jvm/java-21-openjdk-amd64,$(if $(wildcard /usr/lib/jvm/java-17-openjdk-amd64/bin/javac),/usr/lib/jvm/java-17-openjdk-amd64,))

# Signing configuration. Change these for production releases.
# Keystore file is generated automatically by the sign-apk target if it does not exist.
# Keep the generated keystore file secret and back it up; losing it prevents publishing
# updates to the existing app on Google Play or sideloaded installs.
KEYSTORE_FILE ?= healthlogin-release.keystore
KEYSTORE_ALIAS ?= healthlogin
# The password is generated by the Makefile when the keystore is created and stored
# in a separate file so special characters do not break shell quoting.
KEYSTORE_PASSWORD_FILE ?= healthlogin-release.password

# Keystore password helper: reads the password file or fails if it is missing.
# This is intentionally a shell command so the password is evaluated after the
# password file has been generated by the keystore target.
KEYSTORE_PASS_CMD = if [ -f '$(KEYSTORE_PASSWORD_FILE)' ]; then cat '$(KEYSTORE_PASSWORD_FILE)'; else echo ""; fi

# Database connection for host-side Go tools (bump-android-version, release).
# The db container does not publish port 5432 to the host (see docker-compose.yml),
# so connect via the container IP. When the container or the .env values are
# unavailable, the variables stay empty and the Go tools fall back to their
# built-in defaults (localhost, healthlogin/healthlogin).
# Note: exported make variables do NOT reach the $(shell) function, so the
# variables are passed to the Go tools explicitly via DB_ENV.
DB_CONTAINER_IP := $(shell docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' healthlogin_db 2>/dev/null)
DB_HOST ?= $(DB_CONTAINER_IP)
DB_USER ?= $(shell grep '^DB_USER=' .env 2>/dev/null | cut -d= -f2-)
DB_PASSWORD ?= $(shell grep '^DB_PASSWORD=' .env 2>/dev/null | cut -d= -f2-)
DB_NAME ?= $(shell grep '^DB_NAME=' .env 2>/dev/null | cut -d= -f2-)
DB_ENV = $(foreach v,DB_HOST DB_USER DB_PASSWORD DB_NAME,$(if $($v),$v='$($v)'))

# Locate build tools for signing. Prefers the newest available version.
BUILD_TOOLS_DIR := $(lastword $(sort $(wildcard $(ANDROID_SDK_PATH)/build-tools/*)))
APKSIGNER := $(BUILD_TOOLS_DIR)/apksigner
ZIPALIGN := $(BUILD_TOOLS_DIR)/zipalign

setup-android:
	@echo "Setting up Capacitor and Android platform..."
	cd frontend && npm install @capacitor/core @capacitor/cli @capacitor/android
	cd frontend && npx cap init healthlogin com.healthlogin.app --web-dir=dist || true
	cd frontend && npx cap add android || true
	@echo "Enabling cleartext traffic in AndroidManifest.xml..."
	node -e "const fs = require('fs'); const file = 'frontend/android/app/src/main/AndroidManifest.xml'; if (fs.existsSync(file)) { let content = fs.readFileSync(file, 'utf8'); if (!content.includes('usesCleartextTraffic')) { content = content.replace('<application', '<application android:usesCleartextTraffic=\"true\"'); fs.writeFileSync(file, content); } }"

build-android:
	@echo "Building frontend for Android..."
	cd frontend && npm run build -- --mode android
	@echo "Syncing assets to Android project..."
	cd frontend && npx cap sync
	@echo "Building debug APK..."
	cd frontend/android && ANDROID_HOME=$(ANDROID_SDK_PATH) JAVA_HOME=$(JAVA_HOME) ./gradlew assembleDebug
	@echo "Copying APK to project root..."
	cp frontend/android/app/build/outputs/apk/debug/app-debug.apk ./healthlogin-app.apk
	@echo "APK built successfully! You can find it at: ./healthlogin-app.apk"

# Fetch the next version code from the database and update build.gradle.
# Fetch the next version code and version name from the database and update build.gradle.
bump-android-version:
	@echo "Fetching next version code and name from database..."
	$(eval NEXT_VERSION_CODE := $(shell cd backend && $(DB_ENV) go run ./cmd/next-version-code))
	$(eval TARGET_VERSION := $(if $(VERSION),$(VERSION),$(shell cd backend && $(DB_ENV) go run ./cmd/next-version-name 2>/dev/null || echo "1.0.0")))
	@if [ -z "$(NEXT_VERSION_CODE)" ]; then \
		echo "ERROR: Could not determine next version code from database"; \
		exit 1; \
	fi
	@echo "Next version code: $(NEXT_VERSION_CODE), version name: $(TARGET_VERSION)"
	cp frontend/android/app/build.gradle frontend/android/app/build.gradle.bak
	node -e "const fs = require('fs'); \
		const file = 'frontend/android/app/build.gradle'; \
		let content = fs.readFileSync(file, 'utf8'); \
		content = content.replace(/versionCode\s+\d+/, 'versionCode $(NEXT_VERSION_CODE)'); \
		content = content.replace(/versionName\s+\"[^\"]+\"/, 'versionName \"$(TARGET_VERSION)\"'); \
		fs.writeFileSync(file, content);"
	@echo "build.gradle updated"

build-android-release: bump-android-version
	@echo "Building frontend for Android..."
	cd frontend && npm run build -- --mode android
	@echo "Syncing assets to Android project..."
	cd frontend && npx cap sync
	@echo "Building release APK..."
	cd frontend/android && ANDROID_HOME=$(ANDROID_SDK_PATH) JAVA_HOME=$(JAVA_HOME) ./gradlew assembleRelease
	@echo "Signing release APK..."
	$(MAKE) sign-apk
	@echo "Release APK built successfully!"

# Generate a release keystore if it does not exist.
$(KEYSTORE_PASSWORD_FILE):
	@echo "Generating keystore password file: $(KEYSTORE_PASSWORD_FILE)"
	@openssl rand -base64 24 | tr -d '\n=+/' > '$(KEYSTORE_PASSWORD_FILE)'
	@chmod 600 '$(KEYSTORE_PASSWORD_FILE)'

$(KEYSTORE_FILE): $(KEYSTORE_PASSWORD_FILE)
	@echo "Generating release keystore: $(KEYSTORE_FILE)"
	@KEYSTORE_PASSWORD=$$($(KEYSTORE_PASS_CMD)); \
	if [ -z "$$KEYSTORE_PASSWORD" ]; then \
		echo "ERROR: Keystore password is empty"; \
		exit 1; \
	fi; \
	keytool -genkey -v \
		-keystore '$(KEYSTORE_FILE)' \
		-alias '$(KEYSTORE_ALIAS)' \
		-keyalg RSA \
		-keysize 2048 \
		-validity 10000 \
		-storepass "$$KEYSTORE_PASSWORD" \
		-keypass "$$KEYSTORE_PASSWORD" \
		-dname "CN=HealthLogin, OU=Development, O=HealthLogin, L=Unknown, ST=Unknown, C=RU"
	@echo "Keystore created: $(KEYSTORE_FILE)"
	@echo "Store the password from $(KEYSTORE_PASSWORD_FILE) and the keystore file in a secure location."

sign-apk: $(KEYSTORE_FILE)
	@if [ ! -f "frontend/android/app/build/outputs/apk/release/app-release-unsigned.apk" ]; then \
		echo "ERROR: Unsigned release APK not found. Run 'make build-android-release' first."; \
		exit 1; \
	fi
	@KEYSTORE_PASSWORD=$$($(KEYSTORE_PASS_CMD)); \
	if [ -z "$$KEYSTORE_PASSWORD" ]; then \
		echo "ERROR: Keystore password not found in $(KEYSTORE_PASSWORD_FILE)"; \
		exit 1; \
	fi; \
	echo "Aligning release APK..."; \
	$(ZIPALIGN) -f -v 4 \
		frontend/android/app/build/outputs/apk/release/app-release-unsigned.apk \
		frontend/android/app/build/outputs/apk/release/app-release-aligned.apk; \
	echo "Signing release APK..."; \
	$(APKSIGNER) sign \
		--ks '$(KEYSTORE_FILE)' \
		--ks-key-alias '$(KEYSTORE_ALIAS)' \
		--ks-pass pass:"$$KEYSTORE_PASSWORD" \
		--key-pass pass:"$$KEYSTORE_PASSWORD" \
		--out ./healthlogin-app.apk \
		frontend/android/app/build/outputs/apk/release/app-release-aligned.apk; \
	echo "Signed APK saved to: ./healthlogin-app.apk"; \
	echo "Keystore: $(KEYSTORE_FILE)"; \
	echo "Password file: $(KEYSTORE_PASSWORD_FILE)"

release: release-android

release-android: build-android-release
	@echo "Registering APK release in database..."
	@BUILT_VERSION_CODE=$$(node -e "const fs=require('fs'); const c=fs.readFileSync('frontend/android/app/build.gradle','utf8'); const m=c.match(/versionCode\\s+(\\d+)/); console.log(m ? m[1] : '');"); \
	BUILT_VERSION_NAME=$$(node -e "const fs=require('fs'); const c=fs.readFileSync('frontend/android/app/build.gradle','utf8'); const m=c.match(/versionName\\s+\"([^\"]+)\"/); console.log(m ? m[1] : '');"); \
	if [ -z "$$BUILT_VERSION_CODE" ]; then \
		echo "ERROR: Could not extract versionCode from build.gradle"; \
		mv frontend/android/app/build.gradle.bak frontend/android/app/build.gradle || true; \
		exit 1; \
	fi; \
	echo "Built version code: $$BUILT_VERSION_CODE, version name: $$BUILT_VERSION_NAME"; \
	cd backend && $(DB_ENV) go run ./cmd/release \
		-apk ../healthlogin-app.apk \
		-platform android \
		-version-name "$$BUILT_VERSION_NAME" \
		-version-code "$$BUILT_VERSION_CODE" \
		-releases-dir ../releases \
		-release-notes "$(RELEASE_NOTES)" \
		$(if $(FORCE_UPDATE),-force-update)
	@echo "Release registered successfully."
	@echo "Restoring original build.gradle..."
	mv frontend/android/app/build.gradle.bak frontend/android/app/build.gradle

setup-smtp-creds:
	@echo "Ensuring SMTP user credentials in mailserver..."
	@SMTP_USER=$$(grep '^SMTP_USER=' .env 2>/dev/null | cut -d= -f2-); \
	SMTP_USER=$${SMTP_USER:-system@moya-usluga.ru}; \
	SMTP_PASS=$$(grep '^SMTP_PASSWORD=' .env 2>/dev/null | cut -d= -f2-); \
	if [ -n "$$SMTP_PASS" ]; then \
		$(call compose,exec -T mailserver /bin/maddy -config /data/maddy.conf creds remove --yes "$$SMTP_USER" 2>/dev/null || true) ; \
		printf "%s\n%s\n" "$$SMTP_PASS" "$$SMTP_PASS" | $(call compose,exec -T mailserver /bin/maddy -config /data/maddy.conf creds create "$$SMTP_USER" 2>/dev/null || true) ; \
		echo "SMTP credentials synchronized for $$SMTP_USER."; \
	fi

# Start backend, frontend and database via Docker Compose
start:
	@echo "Starting backend, frontend and database..."
	$(call compose,up -d --build)
	@$(MAKE) setup-smtp-creds || true
	@echo "Services started."
	@echo "  Backend:  https://localhost:8088"
	@echo "  Frontend: https://localhost:8443"

# Start backend with Delve remote debugger, frontend and database via Docker Compose
start-debug:
	@echo "Starting backend with Delve debugger, frontend and database..."
	$(call compose,-f docker-compose.debug.yml up -d --build)
	@echo "Debug services started."
	@echo "  Backend:  https://localhost:8088"
	@echo "  Frontend: https://localhost:8443"
	@echo "  Delve:    localhost:40000"

# Stop all running services
stop:
	@echo "Stopping all services..."
	$(call compose,down)
	@echo "Services stopped."

# Register existing APK file into DB and releases directory.
# The release binary is built into the backend image, so we run it via
# docker compose run with temporary mounts for the APK and build.gradle.
register-release:
	@echo "Registering APK release in database..."
	@if [ -f healthlogin-app.apk ]; then \
		$(call compose,run --rm \
			-v $(PWD)/healthlogin-app.apk:/app/healthlogin-app.apk:ro \
			-v $(PWD)/frontend/android/app/build.gradle:/app/frontend/android/app/build.gradle:ro \
			backend \
			/app/release \
			-apk /app/healthlogin-app.apk \
			-platform android \
			-releases-dir /app/releases \
			-version-file /app/frontend/android/app/build.gradle) ; \
		echo "Release registered."; \
	else \
		echo "healthlogin-app.apk not found, skipping release registration."; \
	fi

# Restart all running services.
#
# The endpoint-file check is listed first on purpose. `start` depends on it too,
# but by then `stop` has already torn the stack down — a broken bind mount would
# take the whole application offline and then refuse to bring it back. Failing
# here leaves the running containers untouched.
restart: stop start register-release
	@echo "Services restarted."

# Show logs from all services
logs:
	$(call compose,logs -f)

# Apply pending database migrations.
# The backend also does this on start; this target is for applying them without
# restarting the service. Applied versions are tracked in schema_migrations, so
# running it twice is a no-op.
migrate:
	@echo "Running database migrations..."
	$(call compose,exec backend ./migrate)
	@echo "Migrations applied."

# Enable pg_stat_statements, the per-query time record that makes a slow
# database readable after the fact ("which query burned the time?").
#
# It is a separate target rather than a migration on purpose: the extension can
# only be created once the library is preloaded (see the db service's command in
# docker-compose.yml), and a migration that fails on a host without it would
# stop the backend from starting at all. Run once per database, after a compose
# up that picked up the new command.
pg-stats:
	@echo "Enabling pg_stat_statements..."
	$(call compose,exec db psql -U $${DB_USER:-healthlogin} -d $${DB_NAME:-healthlogin} \
		-c "CREATE EXTENSION IF NOT EXISTS pg_stat_statements;")
	@echo "Enabled. Top queries by total time:"
	@echo "  make pg-top"

# The queries that cost the most wall-clock time since the last reset. This is
# the first thing to look at after a load test.
PG_TOP_SQL = SELECT calls, round(total_exec_time::numeric, 1) AS total_ms, round(mean_exec_time::numeric, 2) AS mean_ms, left(query, 120) AS query FROM pg_stat_statements ORDER BY total_exec_time DESC LIMIT 20;

pg-top:
	$(call compose,exec db psql -U $${DB_USER:-healthlogin} -d $${DB_NAME:-healthlogin} -c "$(PG_TOP_SQL)")

# Check that stored balances still equal the sum of the transaction log.
# Exits non-zero when they do not, so it can be used as a deployment gate.
# The backend also runs this nightly and logs the result.
reconcile:
	@echo "Reconciling balances against the ledger..."
	$(call compose,exec backend ./reconcile)

# --- Monitoring -----------------------------------------------------------
#
# The stack is an overlay on the main compose file rather than part of it, so
# the application can be started and restarted without it. Every UI binds to
# 127.0.0.1; reach them through an SSH tunnel (see doc/monitoring.md).

# Monitoring secrets live in their own env file. The application deploy
# rewrites .env wholesale on every run, so anything the monitoring stack needs
# would be lost the next time the two deploys race — which they now do, since
# they run as parallel CI jobs.
#
# Passing any --env-file stops Compose from loading .env automatically, so .env
# is passed explicitly whenever it exists; values in the later file win.
MONITORING_ENV = $(if $(wildcard .env),--env-file .env) $(if $(wildcard .env.monitoring),--env-file .env.monitoring)
MONITORING_COMPOSE = $(MONITORING_ENV) -f docker-compose.yml -f docker-compose.monitoring.yml
MONITORING_SERVICES = prometheus alertmanager grafana opsbot node-exporter cadvisor postgres-exporter nginx-exporter blackbox-exporter

# --no-deps keeps this from starting or recreating db and frontend: the
# application deploy may be running at the same time, and two processes bringing
# the same containers up is how you get a half-restarted stack. The exporters
# retry until their target is back, which is the correct behaviour anyway.
monitoring-up:
	@echo "Starting Prometheus, Grafana, Alertmanager and exporters..."
	$(call compose,$(MONITORING_COMPOSE) up -d --build --no-deps $(MONITORING_SERVICES))
	@echo "Monitoring started (all bound to localhost):"
	@echo "  Grafana:      http://127.0.0.1:3000"
	@echo "  Prometheus:   http://127.0.0.1:9090"
	@echo "  Alertmanager: http://127.0.0.1:9093"

monitoring-down:
	@echo "Stopping monitoring only; the application keeps running."
	$(call compose,$(MONITORING_COMPOSE) stop $(MONITORING_SERVICES))
	$(call compose,$(MONITORING_COMPOSE) rm -f $(MONITORING_SERVICES))

monitoring-logs:
	$(call compose,$(MONITORING_COMPOSE) logs -f prometheus alertmanager grafana opsbot)

# Reload Prometheus after editing rules, without dropping the series database.
monitoring-reload:
	@echo "Reloading Prometheus configuration and rules..."
	@curl -sf -X POST http://127.0.0.1:9090/-/reload && echo "Reloaded." || \
		echo "Reload failed — check that Prometheus is running and the config parses."

# Validate the rule files before they are deployed. A rule with a typo is
# silently never evaluated, which is the worst failure mode monitoring has.
# Expanded on the host: the prometheus image has no shell to glob with, and a
# literal wildcard would be passed straight through to promtool.
RULE_TESTS = $(patsubst monitoring/prometheus/%,/etc/prometheus/%,$(wildcard monitoring/prometheus/rules/tests/*.yml))

monitoring-check:
	@echo "Checking Prometheus configuration and alert rules..."
	docker run --rm \
		-v $(PWD)/monitoring/prometheus:/etc/prometheus:ro \
		--entrypoint promtool prom/prometheus:v3.1.0 \
		check config /etc/prometheus/prometheus.yml
	@echo "Running alert rule unit tests..."
	docker run --rm \
		-v $(PWD)/monitoring/prometheus:/etc/prometheus:ro \
		--entrypoint promtool prom/prometheus:v3.1.0 \
		test rules $(RULE_TESTS)
	@echo "Configuration and rules are valid."

clean:
	rm -f healthlogin-app.apk
	rm -f healthlogin-release.keystore
	rm -f healthlogin-release.password
	rm -f frontend/android/app/build/outputs/apk/release/app-release-aligned.apk
	rm -f frontend/android/app/build.gradle.bak

# The monitoring stack is a second overlay in the same Compose project, so any
# command that passes only docker-compose.yml sees its containers as "orphans"
# and says so on every run. They are not orphans — they are deliberately there,
# and Compose has no way to be told that.
#
# The warning is worth silencing rather than living with: it fires on every
# start, restart and release registration, and a warning that always fires is
# one nobody reads.
#
# NEVER act on what that warning suggests. `docker compose --remove-orphans`
# with only the base file DELETES the entire monitoring stack — Prometheus data,
# Grafana dashboards, Alertmanager silences. Verified: a plain `down` with the
# base file leaves the monitoring containers running, so the application can be
# stopped and restarted safely; only --remove-orphans is destructive here.
export COMPOSE_IGNORE_ORPHANS = true

# Helper: use docker compose if available, fall back to docker-compose
define compose
$(if $(shell docker compose version >/dev/null 2>&1 && echo ok),docker compose $(1),docker-compose $(1))
endef
