# Общие настройки Gradle для всего проекта.

# Пользователям IDE (например, Android Studio):
# настройки Gradle, заданные через IDE, *перекрывают*
# любые настройки из этого файла.

# Подробнее о настройке окружения сборки:
# http://www.gradle.org/docs/current/userguide/build_environment.html

# Задаёт аргументы JVM для процесса-демона.
# Особенно полезно для тонкой настройки памяти.
org.gradle.jvmargs=-Xmx1536m

# Если задано, Gradle будет работать в экспериментальном параллельном режиме.
# Этот параметр стоит использовать только с независимыми проектами. Подробнее:
# http://www.gradle.org/docs/current/userguide/multi_project_builds.html#sec:decoupled_projects
# org.gradle.parallel=true

# Структура пакетов AndroidX: яснее видно, какие пакеты идут с операционной
# системой Android, а какие упаковываются в APK приложения
# https://developer.android.com/topic/libraries/support-library/androidx-rn
android.useAndroidX=true
